### PR TITLE
added functions to README for prrr review

### PR DESCRIPTION
**Pull request by TheLady**
per feedback on yesterday's prrr submission

### CODE REVIEW

**Review by jrobcodes — COMMENTED** [review]
I'm surprised at the state of this project - it looks like another update to the learning contract, without any implementation done yet?  Please reach out to the coaches if you need help getting started - I would expect much more done by this point in the week on a project like this.

**Comment by TheLady** [comment]
We've done more than that - you can take a look at our repo if you'd like, but it has a lot of loose ends. We probably focussed too much on trying to implement the learning contract correctly. Here's a link to what we pushed before we left yesterday.  https://github.com/TheLady/moldy-zorilla/tree/moldy-zorilla-wb

**Comment by TheLady** [comment]
Thanks for taking a look.

**Comment by jrobcodes** [comment]
Ah, thank you, that makes so much more sense!  Consider adding the README updates along with the code changes so that its clear what is being implemented.

**Pull request merged**
