### PR TITLE
added white space to prepare for prrr submision

### PR DESCRIPTION
**Pull request by TheLady**

### CODE REVIEW

**Comment by rae-ralston** [comment]
https://github.com/TheLady/moldy-zorilla/tree/contract

Some of your headers are off, like this line: 
how to publish a package to NPM? ## Specifications ### Required

You also don't have any specifications?? On this branch at least... Am i missing something? 
Maybe specify which functions you're going to write?

**Review by DianaVashti — CHANGES_REQUESTED** [review]
How many functions do you plan to do for the week. You should commit to a hard number today. Also, what testing suite do you plan to use? I would like to see a list of all the functions you aim to tackle this week included in the read me with an unchecked box that you can check off as you go.

**Comment by TheLady** [comment]
Hi Di,

Thanks for reviewing these. We didn't have a list of functions in our so I am wondering if that changes what you were expecting to see. Here is a link to our project on GuildCrafts/web-development https://github.com/GuildCrafts/web-development-js/issues/37 . I also submitted the correct PR to prrr this time :-).

**Comment by TheLady** [comment]
Thanks, Rachel! I also submitted the correct PR to prrr this time :-).

**Pull request closed without merging**
